// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU5UFQR9QSb_zCXU0516RBiNohtqgGRTc',
    appId: '1:807576823468:web:46346bd1623d6bc9546109',
    messagingSenderId: '807576823468',
    projectId: 'rebinit-app',
    authDomain: 'rebinit-app.firebaseapp.com',
    storageBucket: 'rebinit-app.firebasestorage.app',
    measurementId: 'G-T8XXNP6NRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsAaf8NvlQNoQfNPGVp8EGnbW8WEseC-0',
    appId: '1:807576823468:android:d051f14ef3d7db57546109',
    messagingSenderId: '807576823468',
    projectId: 'rebinit-app',
    storageBucket: 'rebinit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW4alJjjv40VB_nD_yMcplHHDfHXqkSUI',
    appId: '1:807576823468:ios:208e98e3ad9aecde546109',
    messagingSenderId: '807576823468',
    projectId: 'rebinit-app',
    storageBucket: 'rebinit-app.firebasestorage.app',
    iosBundleId: 'com.rebinittechnologies.rebinitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW4alJjjv40VB_nD_yMcplHHDfHXqkSUI',
    appId: '1:807576823468:ios:208e98e3ad9aecde546109',
    messagingSenderId: '807576823468',
    projectId: 'rebinit-app',
    storageBucket: 'rebinit-app.firebasestorage.app',
    iosBundleId: 'com.rebinittechnologies.rebinitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU5UFQR9QSb_zCXU0516RBiNohtqgGRTc',
    appId: '1:807576823468:web:1662c20dc45eead7546109',
    messagingSenderId: '807576823468',
    projectId: 'rebinit-app',
    authDomain: 'rebinit-app.firebaseapp.com',
    storageBucket: 'rebinit-app.firebasestorage.app',
    measurementId: 'G-WJPMS4P8PV',
  );
}
