import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:rebinit_app/screens/auth/signup_screen.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'screens/onboarding/onboarding_screen.dart';
import 'screens/auth/login_screen.dart';
import 'screens/admin_dashboard_screen.dart';
import 'widgets/bottom_navbar.dart'; // ✅ import wrapper
import 'firebase_options.dart'; // generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Check if user has seen onboarding
  final prefs = await SharedPreferences.getInstance();
  final hasSeenOnboarding = prefs.getBool('hasSeenOnboarding') ?? false;

  // Check if user is already logged in
  final currentUser = FirebaseAuth.instance.currentUser;

  runApp(MyApp(
    showOnboarding: !hasSeenOnboarding,
    currentUser: currentUser,
  ));
}

class MyApp extends StatelessWidget {
  final bool showOnboarding;
  final User? currentUser;

  const MyApp({super.key, required this.showOnboarding, this.currentUser});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ReBinIt',
      theme: ThemeData(primarySwatch: Colors.green),
      debugShowCheckedModeBanner: false,
      initialRoute: showOnboarding
          ? '/onboarding'
          : (currentUser != null ? '/main' : '/login'), // ✅ go to wrapper
      routes: {
        '/onboarding': (_) => const OnboardingScreen(),
        '/login': (_) => const LoginScreen(),
        '/register': (_) => const SignupScreen(),
        '/main': (_) => MainNavigationWrapper(userId: currentUser?.uid ?? ''), // ✅ wrapper with navbar + drawer
        '/admin': (_) => AdminDashboardScreen(adminId: currentUser?.uid ?? ''),
      },
    );
  }
}
